name: appunti_web_frontend
description: E ti laurei pure, bastardo.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  mime: ^0.9.0
  dio: ^3.0.0
  url_launcher: ^5.5.0
  file_picker: ^2.0.0
  fluro: ^1.6.0
  transparent_image:
  draggable_scrollbar: ^0.0.4
  string_trimmer:
  flutter:
    sdk: flutter
  # cupertino_icons: ^0.1.3 # Per il momento lo tolgo, se vogliamo fare una versione iOS lo rimettiamo
  # flutter_secure_storage: ^3.3.3 # Per l'app mobile
  # path_provider: ^1.6.11 # Per l'app mobile


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  uses-material-design: true
